# Config file for automatic testing at travis-ci.org

language: python
sudo: required
dist: trusty

python:
    - 3.6


before_install:
    - sudo -E apt-add-repository -y "ppa:ubuntu-toolchain-r/test"
    - sudo apt-get update
    - sudo apt-get install gcc-4.9 gfortran-4.9
    - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 60 --slave /usr/bin/gfortran gfortran /usr/bin/gfortran-4.9
    - sudo ln -sf /usr/bin/gcc-4.9 /usr/bin/gcc
    - sudo ln -sf /usr/bin/gfortran-4.9 /usr/bin/gfortran
    - /usr/bin/gcc --version
    - /usr/bin/gfortran --version
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda info -a

install:
    - conda create -q -n test_env python=$TRAVIS_PYTHON_VERSION numpy scipy libgfortran nose pytest
    - source activate test_env
    - find /usr -name "*gfortran*"
    - make all
    - make install

script:
    - cd wrappers/python
    - python basictest.py
